[tool.poetry]
name = "rsp-aqm"
version = "0.1.0"
description = ""
authors = ["Calvin Lynch"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
influxdb-client = "^1.46.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
